#!/bin/bash
: "${LIRC_DEVICE:=/dev/lirc0}"
IR_CTL="ir-ctl"
if [[ $QUERY_STRING =~ (^|&)keymap=([^&]*) ]]; then
  ir_ctl_keymap="/etc/rc_keymaps/${BASH_REMATCH[2]}.sh"
  keymap="/etc/rc_keymaps/${BASH_REMATCH[2]}.toml"
  if [[ -f "$ir_ctl_keymap" ]]; then
    IR_CTL="$ir_ctl_keymap"
  elif [[ ! -f "$keymap" ]]; then
    echo Status: 404 Keymap not found
    echo
    echo Keymap not found
    exit 2
  fi
else
  echo Status: 400 Bad Request
  echo
  echo Bad Request: Missing keymap
  cat >&2
  exit 1
fi
if [[ $QUERY_STRING =~ (^|&)keycode=([^&]*) ]]; then
  keycode="${BASH_REMATCH[2]}"
  # https://unix.stackexchange.com/questions/159253/decoding-url-encoding-percent-encoding
  keycode=$(keycode=${keycode//+/ }; printf '%b' "${keycode//%/\\x}")
else
  echo Status: 400 Bad Request
  echo
  echo Bad Request: Missing keycode!
  exit 1
fi
status="200 OK"
declare -a delays=()
if [[ $QUERY_STRING =~ (^|&)delays=([^&]*) ]]; then
  delay_str=${BASH_REMATCH[2]}
  shopt -s nocasematch
  delay_str=${delay_str//%2c/,}
  OIFS=$IFS
  IFS=,
  delays=($delay_str)
  IFS=$OIFS
fi
redirect=
if [[ $QUERY_STRING =~ (^|&)redirect=([^&]*) ]]; then
  redirect=${BASH_REMATCH[2]}
  status="302 Redirect"
fi
log=()
out="$("${IR_CTL}" -d "${LIRC_DEVICE}" -k "$keymap" -K "$keycode" 2>&1)"
exit_status=$?
if [[ -n "${out}" ]]; then
  log+=("$out")
fi
if [[ $exit_status -ne 0 ]]; then
  status="500 Internal Server Error"
  log+=("exit_status = $exit_status")
fi
for delay in "${delays[@]}"; do
  sleep "$delay"
  out="$("${IR_CTL}" -d "${LIRC_DEVICE}" -k "$keymap" -K "$keycode" 2>&1)"
  exit_status=$?
  if [[ -n "${out}" ]]; then
    log+=("$out")
  fi
  if [[ $exit_status -ne 0 ]]; then
    status="500 Internal Server Error"
    log+=("exit_status = $exit_status")
  fi
done
echo "Status: ${status}"
echo "Content-Type: text/plain"
if [[ -n "$redirect" ]]; then
  echo "Location: http://${SERVER_ADDR}${redirect}"
  echo
  exit 0
fi
echo
for l in "${log[@]}"; do
  echo "$l"
done
exit 0
